name: panic_button
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Gesti칩n de estado y l칩gica
  get: ^4.7.2
  provider: ^6.0.3

  # Persistencia de datos
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Servicios externos
  appwrite: ^15.0.2
  url_launcher: ^6.1.7

  # Geolocalizaci칩n y mapas
  location: ^8.0.0
  flutter_map: ^4.0.0
  latlong2: ^0.8.1

  # Gr치ficos
  fl_chart: ^0.66.0

  # Iconos
  cupertino_icons: ^1.0.8
  sensors_plus: ^6.1.1
  speech_to_text: ^7.0.0
  collection: ^1.16.0
  image_picker: ^0.8.7+3
  google_fonts: ^4.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.14
  patch_package: ^0.0.8

dependency_overrides:
  flutter_web_auth_2: ^4.1.0

flutter:
  uses-material-design: true
